language: node_js
node_js:
  - 10.15.2
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES
  local_dir: public
  keep_history: true
  on:
    branch: master
    
