language: node_js
node_js:
  - 12.18.3
script: make pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES
  local_dir: build
  keep_history: true
  on:
    branch: master
    
